# See: https://circleci.com/docs/2.0/language-python/

version: 2.1
jobs:
  documentation:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - run:
          name: Update apt-get
          command: |
            sudo apt update

      - run:
          name: Install Graphviz
          command: |
            sudo apt install graphviz libgraphviz-dev

      - run:
          name: Install pysal dependencies
          command: |
            sudo apt install libspatialindex-dev

      - restore_cache:
          keys:
            - uv-cache-v1

      - run:
          name: Install uv
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV

      - run:
          name: Install dependencies and build docs
          command: |
            uv sync --extra default --extra test --extra extra --extra example --extra doc
            source .venv/bin/activate
            # Install trusted backends, but not their dependencies.
            # We only need to use the "networkx.backend_info" entry-point.
            # This is the nightly wheel for nx-cugraph.
            uv pip install nx-cugraph-cu11 --extra-index-url https://pypi.anaconda.org/rapidsai-wheels-nightly/simple --no-deps --prerelease=allow
            # Development version of GraphBLAS backend
            uv pip install git+https://github.com/python-graphblas/graphblas-algorithms.git@main --no-deps
            # Development version of nx-parallel backend
            uv pip install git+https://github.com/networkx/nx-parallel.git@main --no-deps
            # Build docs
            # NOTE: bad interaction w/ blas multithreading on circleci
            export OMP_NUM_THREADS=1
            make -C doc/ html

      - save_cache:
          key: uv-cache-v1
          paths:
            - ~/.cache/uv

      - store_artifacts:
          path: doc/build/html

  image:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - run:
          name: Install uv
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV

      - run:
          name: Install dependencies and test drawing
          command: |
            uv sync --extra default --extra test
            source .venv/bin/activate
            uv pip install pytest-mpl  # NOTE: specified here to avoid confusing conda
            pytest --mpl --mpl-generate-summary=html --mpl-results-path=results --pyargs networkx.drawing

      - store_artifacts:
          path: results

workflows:
  documentation_and_image_comparison:
    jobs:
      - documentation
      - image
