name: Test with Nightly wheels
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  nightly:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          pip install --upgrade uv
          uv pip install  --system -U --pre --i https://pypi.org/simple --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple -r requirements/default.txt
          uv pip install --system --pre -r requirements/test.txt
          uv pip install --system .
          uv pip list

      - name: Test NetworkX
        run: |
          pytest --doctest-modules --durations=10 --pyargs networkx
