name: Run test suite in random order
on:
  schedule:
    # Run this workflow once a day
    - cron: "0 0 * * *"

jobs:
  randomize-test-order:
    if: github.repository == 'networkx/networkx'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true

      - name: Sync dependencies
        run: |
          uv sync --extra default --extra test --extra test-extras
          uv pip list

      - name: Run tests
        run: pytest --doctest-modules --durations=10 --pyargs networkx
